import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/authprovider";
import { CartProvider } from "./context/CartContext";
import { AudioProvider } from "./context/AudioContext";
import ClientLayout from "./ClientLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "On The Track",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
            <AudioProvider>
              <ClientLayout>{children}</ClientLayout>
            </AudioProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}